# frozen_string_literal: true

source "https://rubygems.org"

gem "capybara", "3.33.0"
gem "rspec", "3.10.0"
gem "selenium-webdriver", "3.142.7"
gem "ffi", "1.12.2"
gem 'cpf_utils'

group :development do 
    gem "better_errors"
    gem "binding_of_caller"
end
