# frozen_string_literal: true

source 'https://rubygems.org'
# git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'allure-cucumber'
gem 'appium_lib'
gem 'capybara'
gem 'cpf_cnpj'
gem 'cucumber'
gem 'cucumber-rails'
gem 'ffi'
gem 'fiddle'
gem 'rails'
gem 'rspec'
gem 'selenium-webdriver'
gem 'watir-scroll'
gem 'webdrivers', '~> 5.0'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
end
